#FROM tomcat-base:prod-latest
FROM localhost:5000/tomcat-base:prod-latest
MAINTAINER david100gom <david100gom@gmail.com>

ADD index.jsp /home/web/WebContent/
ADD index.html /usr/local/server/apache/htdocs/

EXPOSE 80
EXPOSE 443
